### ISSUE TITLE
Add support for -LiteralPath to Registry Functions

### ISSUE THREAD

**Issue by midiman369** [DominikBritz/DSC#4]
Hi, This module is fantastic!  However, I ran into an issue with the registry portion regarding behavior of Get-ChildItem, Get-Item, and Get-ItemProperty.

Registry key names / "containers" can have an asterisk in their name.  This causes errors.  Adding the -LiteralPath to each call to those functions resolves the issue.

Attached is a hastily edited version that resolved the issue for me.

[Get-DSCConfigurationFromRegistry.txt](https://github.com/DominikBritz/DSC/files/450091/Get-DSCConfigurationFromRegistry.txt)

**Comment by DominikBritz** [comment]
Fixed
